### ISSUE TITLE
Visual Studio找不到附加到Unity进程

### ISSUE THREAD

**Issue by straywriter** [bodong1987/UnrealSharp#3]
![image](https://github.com/bodong1987/UnrealSharp/assets/48555863/93a84c9b-ee59-437a-965c-fc3a086a0071)

如图，C#代码可以执行到，但是vs里面无法找到这个继承

**Comment by straywriter** [comment]
这个调试的原理是什么

**Comment by straywriter** [comment]
![image](https://github.com/bodong1987/UnrealSharp/assets/48555863/ff20d26f-f174-4fd2-b856-a13936b6257a)
我启动一个unity工程，是可以找到的

**Comment by bodong1987** [comment]
> 这个调试的原理是什么

基于socket的，我在升级了ue5.4之后也发现了这个问题，暂时还没有时间去查。之前的版本还是可以的。后续我会抽时间找到并修复这个问题。

**Comment by bodong1987** [comment]
> ![image](https://private-user-images.githubusercontent.com/48555863/347316256-ff20d26f-f174-4fd2-b856-a13936b6257a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTk0NDIsIm5iZiI6MTcyMTE5OTE0MiwicGF0aCI6Ii80ODU1NTg2My8zNDczMTYyNTYtZmYyMGQyNmYtZjE3NC00ZmQyLWI4NTYtYTEzOTM2YjYyNTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA2NTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZGNmNDliNTRmOTc0MmJhYmY1ZTEzOGJjYmM2YWNlMDMxY2IyZjE2OTA5YjFmZGYxYTZjNmNhZDRmYjcyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9u-4NDKgUfWJOWhqjWQZpy1JfeTnE5XhMhdESnbRa1c) 我启动一个unity工程，是可以找到的

能否告知我你使用的Visual Studio版本号呢，这可能是因为vs的unity调试插件升级了的缘故。

**Comment by straywriter** [comment]
![image](https://github.com/user-attachments/assets/531d04bc-3d5b-47e4-8efe-1f92002b5d20)

**Comment by bodong1987** [comment]
> ![image](https://private-user-images.githubusercontent.com/48555863/349393307-531d04bc-3d5b-47e4-8efe-1f92002b5d20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTk1ODgsIm5iZiI6MTcyMTE5OTI4OCwicGF0aCI6Ii80ODU1NTg2My8zNDkzOTMzMDctNTMxZDA0YmMtM2Q1Yi00N2U0LThlZmUtMWY5MjAwMmI1ZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA2NTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDBkNTU2MzVhNmM0OGZkMzI1ZGZiZmNmMmNkNmRkNjBmM2M0YTI0NGVlNGUwZGM5ZGU5N2E1MmZhNTdmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FLmCCv7mfxpu2bNng6yt3avWPj65mnOS0dI-felDhYU)

---
问题在最新版本的C++代码更新后即可解决。关于这个问题的一些原理和实现方法你可以参考我的中文博客： [https://www.cnblogs.com/bodong/p/17962564](https://www.cnblogs.com/bodong/p/17962564)
感谢反馈。
